### ISSUE TITLE
PlatformExceptionError

### ISSUE THREAD

**Issue by deshario** [googlecodelabs/google-maps-in-flutter#8]
**I'm using ```  google_maps_flutter: ^0.5.11 ```**

I just wanna know that how can i fix it .. thankx

```
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

class Mapper extends StatefulWidget {
  @override
  _MapperState createState() => _MapperState();
}

class _MapperState extends State<Mapper> {

  static const LatLng centerMap = const LatLng(13.756676, 100.501922);

  CameraPosition cameraPosition = CameraPosition(
    target:centerMap,
    zoom:12.0,
  );

  Widget myMap(){
    return GoogleMap(
      mapType: MapType.normal,
      zoomGesturesEnabled: true,
      initialCameraPosition: cameraPosition,
      onMapCreated: (GoogleMapController googleMapController){},
      markers: ewtcMarker(),
    );
  }

  Set<Marker> ewtcMarker(){
    return <Marker>[
      Marker(
        position: centerMap,
        markerId: MarkerId('idEWTC'),
      )
    ].toSet();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Column(
          children: <Widget>[
            Expanded(
              flex: 5,
              child: myMap(),
            ),
            Expanded(
              flex: 2,
              child: Center(
                child: Text('Scan Result'),
              ),
            ),
            FloatingActionButton(
              onPressed: () {
                debugPrint('Clicked');
              },
              child: Icon(Icons.add),
            ),
          ],
        ));
  }
}

```
![ERROR](https://user-images.githubusercontent.com/11426727/71523451-b7932e80-28fb-11ea-86bc-82d219e1b588.png)

**Comment by domesticmouse** [comment]
I have no idea what is going wrong here. At a guess, the plugin has changed since I wrote the codelab and it is time I updated it.

**Comment by deshario** [comment]
I cant use google maps anymore .. because of  ```Unhandled Exception: PlatformException(error, Trying to create a platform view of unregistered type: plugins.flutter.io/google_maps, null)``` ... Is there any way to solve it .. I dont have idea what is going on 

Below is my dependencies that i used if there is somethng related

```
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.15.0+1
  provider: ^3.1.0+1
  firebase_database: ^3.1.0
  flutter_svg: ^0.15.0
  intl: ^0.16.0
  percent_indicator: ^2.1.1+1
  qr_code_scanner: 0.0.12
  assets_audio_player: ^1.0.1
  fluro: ^1.5.1
  google_maps_flutter: ^0.5.11
```


Or there is there any other similar to google_maps_flutter
